### ISSUE TITLE
Feedback / Bug Report System 

### ISSUE THREAD

**Issue by ajay-prabhakar** [Chromicle/AmritaResource#1]
Add Feedback / Bug Report System to send the mail directly to Ajayprabhakar369@gmail.com

Also, Add when the app crashes it will automatically send the log messages about the crash

anyone can do this

**Comment by root-ansh** [comment]
I can add the direct mail activity to app. Will need some time since am busy elsewhere, but can do that

**Comment by ajay-prabhakar** [comment]
Yeah ok it's fine take your own time
