### ISSUE TITLE
Add the README.md

### ISSUE THREAD

**Issue by ajay-prabhakar** [Chromicle/AmritaResource#19]
currently, the readme is not good to see so, rewrite the new readme
I am giving one reference [here](https://github.com/amfoss/TempleApp)

**Comment by ajay-prabhakar** [comment]
@root-ansh can you please work on this or else anyone can take this

**Comment by root-ansh** [comment]
Reference readme is good, implementing that won't be difficult.  

Let someone else give it a try for now. If someone else don't respond in next 3 days, I will work on it this sunday

**Comment by bit-man** [comment]
I take it!
Forked to https://github.com/bit-man/AmritaResource.git
