### ISSUE TITLE
Proper internet connection

### ISSUE THREAD

**Issue by ajay-prabhakar** [Chromicle/AmritaResource#4]
Currently, if there is no internet connection to the device when we download the pdf it is coming back previous activity so check for internet connection 
if there is no internet connection do not allow option to download any pdf give toast message that `There is no proper internet connection`

**Comment by ajay-prabhakar** [comment]
@ShivangiSingh17 did you want to work on this

**Comment by rahmatsyam** [comment]
I will try fix it

**Comment by rahmatsyam** [comment]
So this close too frend
